repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: debug-statements
      - id: detect-private-key
      - id: name-tests-test
        args: [--django]
        exclude: ^tests/

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile=black]
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions, flake8-docstrings]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-python-dateutil
          - types-requests
          - types-pyyaml
          - types-pillow
          - types-ujson
          - types-toml
          - types-tabulate
          - types-tzlocal
          - types-pytz
          - types-freezegun
          - types-mock
          - types-python-dateutil
          - types-requests
        args: [--strict, --ignore-missing-imports, --disallow-untyped-defs]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-log-warn
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: [--configfile=pyproject.toml]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.9.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
        args: [--no-verify, --allow-abort, --retry, --retry-failed-update, --hook-mode, commit-msg, --hook]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-toc
          - mdformat-footnote
          - mdformat-frontmatter
        args: [--wrap=88]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint
        args: [--fix, --ignore=CHANGELOG.md]
        exclude: ^(docs|templates)/
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [yaml, json, markdown, html, css, scss, javascript, typescript, jsx, tsx, graphql]
        args: [--write, --prose-wrap=always, --print-width=88]
