version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    ports:
      - "8501:8501"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    command: >
      sh -c "streamlit run app/main.py --server.port=8501 --server.address=0.0.0.0"
    # Uncomment when you add the database
    # depends_on:
    #   - db
    #   - redis
    # environment:
    #   - DATABASE_URL=postgresql://postgres:postgres@db:5432/aivelocity
    #   - REDIS_URL=redis://redis:6379/0

  # Uncomment when you add the database
  # db:
  #   image: timescale/timescaledb:latest-pg14
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: aivelocity
  #   volumes:
  #     - timescaledb_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 5

# volumes:
#   timescaledb_data:
#   redis_data:
